spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yangxianda/config-repo
          username: yxd1599@163.com
          password: YXD19941116@
          basedir: D:\work\spring-boot-demo\SpringCloud_Sell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/